project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('token-auth/', obtain_auth_token, name='token_auth'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('url.urls')),
    path('api/', include('url.api_urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

url/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from url.views import HomeView, ShareView

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('share/<slug:slug_url>', ShareView.as_view(), name='share'),
]

url/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

from url.crypter import Crypter
from url.generator import Generator


class Resource(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    file = models.FileField(blank=True)
    url = models.URLField(blank=True)
    slug_url = models.SlugField(unique=True, null=True, default=Generator.generate)
    password = models.CharField(max_length=128)
    created_at = models.DateTimeField(default=timezone.now)
    expired_at = models.DateTimeField(blank=True)
    visits = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.slug_url} ({self.author})"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.expired_at:
            self.expired_at = timezone.now() + timezone.timedelta(hours=24)
        super().save(force_insert, force_update, using, update_fields)

    def set_password(self, value: str):
        self.password = Crypter(value).encrypt()

    def check_password(self, password: str) -> bool:
        return Crypter(password).equals(self.password)

    def redirect_to(self) -> str:
        if self.url:
            return self.url
        elif self.file is not None:
            return self.file.url
        return ''

    def is_available(self, time=None) -> bool:
        if not time:
            time = timezone.now()
        return self.expired_at > time

    def increment_visits(self):
        self.visits += 1
        self.save()

user_profile/models.py
from django.contrib.auth import get_user_model
from django.db import models


class UserProfile(models.Model):
    profile = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, primary_key=True, related_name='profile')
    meta_data = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.profile}"

url/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Resource


class ResourceForm(forms.ModelForm):
    file = forms.FileField(required=False)
    url = forms.URLField(required=False)

    class Meta:
        model = Resource
        fields = ('file', 'url',)

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('file') and not cleaned_data.get('url'):
            raise ValidationError({'file': 'Field is required', 'url': 'Field is required'})
        return cleaned_data


class ShareResourceForm(forms.ModelForm):
    plain_password = forms.CharField(required=True, label="Write a password")

    class Meta:
        model = Resource
        fields = ('plain_password',)

    def clean(self):
        cleaned_data = super().clean()
        plain_password = cleaned_data.get('plain_password')
        if plain_password and not self.instance.check_password(plain_password):
            raise ValidationError({'plain_password': "Password doesn't match :("})
        return cleaned_data

url/views.py
from django.urls import reverse
from django.views.generic import FormView, DetailView
from django.views.generic.edit import ModelFormMixin

from url.forms import ResourceForm, ShareResourceForm
from url.generator import Generator
from url.models import Resource
from url.signals import update_user_meta


class HomeView(FormView):
    template_name = 'home.html'
    form_class = ResourceForm
    success_url = '/'

    def form_valid(self, form):
        plain_password = Generator.generate(5)

        form.instance.author = self.request.user
        form.instance.set_password(plain_password)
        instance = form.save()

        update_user_meta.send(sender=self.__class__, request=self.request)
        data = {
            "slug_url": self.request.build_absolute_uri(reverse('share', args=[instance.slug_url])),
            "password": plain_password,
        }
        return self.render_to_response({"data": data})


class ShareView(ModelFormMixin, DetailView):
    model = Resource
    template_name = 'share_resource.html'
    slug_url_kwarg = 'slug_url'
    slug_field = 'slug_url'
    form_class = ShareResourceForm
    success_url = '/'

    def get_success_url(self):
        return self.object.redirect_to()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context.update({
            "is_available": self.object.is_available()
        })
        return context

    def form_valid(self, form):
        self.object.increment_visits()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

user_profile/views.py
# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock %}
</main>

<script>
  const fileInput = document.querySelector('#id_file');
  const urlInput = document.querySelector('#id_url');

  (() => {
    function changeFile(e) {
      urlInput.parentElement.style.display = e.target.files.length ? 'none' : '';
    }

    function changeUrl(e) {
      fileInput.parentElement.style.display = e.target.value.length ? 'none' : '';
    }

    if (fileInput && urlInput) {
      fileInput.addEventListener('change', changeFile);
      urlInput.addEventListener('change', changeUrl);
    }
  })();
</script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        Hi {{ user.username }}! <a href="{% url 'logout' %}">Log Out</a>

        {% if form %}
            <form method="post" id="resource-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Send">
            </form>
        {% endif %}
        {% if data %}
            <p>Url: <a href="{{ data.slug_url }}" target="_blank">{{ data.slug_url }}</a></p>
            <p>Password: {{ data.password }}</p>
            <p><a href="/">Add a new one</a></p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/share_resource.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if is_available %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    {% else %}
        <p>Link expired</p>
    {% endif %}
{% endblock %}